#!/usr/bin/env node
/**
 * inject-case.mjs — replace the span between the CASE sentinels in each lesson.
 *
 * Touches nothing outside the sentinels. Idempotent by construction: the block
 * written is a pure function of the generated artifacts, so a second run
 * produces a byte-identical file.
 *
 *   node scripts/inject-case.mjs           write
 *   node scripts/inject-case.mjs --check   report drift, write nothing, exit 1 on any
 *
 * The opening sentinel is followed by a provenance comment carrying the case
 * version and the SHA-256 of the injected block. verify-case.mjs recomputes it.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = join(HERE, '..');
export const LESSONS = ['index.html', 'session-0.1/index.html', 'session-1/index.html',
                        'session-2/index.html', 'session-3/index.html', 'session-4/index.html'];

const facts = JSON.parse(readFileSync(join(HERE, 'case-facts.json'), 'utf8'));
const OPEN  = `<!-- CASE:BEGIN ${facts.case_id} v${facts.case_version} -->`;
const CLOSE = `<!-- CASE:END ${facts.case_id} -->`;

/**
 * buildBlock — the injected region. Facts tab, Structure tab, COLE constant,
 * and the visible version stamp. No script beyond the tab switcher, which is
 * the only interactive part and is written here rather than in the lesson so
 * every lesson gets the identical implementation.
 */
export function buildBlock() {
  const extract   = readFileSync(join(HERE, 'case-extract.html'), 'utf8').trim();
  const flowchart = readFileSync(join(HERE, 'case-flowchart.html'), 'utf8').trim();
  const F = facts.figures;
  const L = [];
  L.push('<div class="case-gen">');
  L.push('  <div class="case-tabs" role="tablist" aria-label="Cole household case">');
  L.push('    <button type="button" class="case-tab on" role="tab" id="caseTabFacts" aria-controls="casePanelFacts" aria-selected="true" tabindex="0">Facts</button>');
  L.push('    <button type="button" class="case-tab" role="tab" id="caseTabStruct" aria-controls="casePanelStruct" aria-selected="false" tabindex="-1">Structure</button>');
  L.push('  </div>');
  L.push('  <div class="case-panel" role="tabpanel" id="casePanelFacts" aria-labelledby="caseTabFacts" tabindex="0">');
  L.push(indent(extract, 4));
  L.push('  </div>');
  L.push('  <div class="case-panel case-off" role="tabpanel" id="casePanelStruct" aria-labelledby="caseTabStruct" tabindex="0">');
  L.push('    <p class="case-h">Structure and annual cash flow. Sheet 1 is ownership after closing with both balance sheets; Sheet 2 is year-1 cash with ribbon widths proportional to dollars.</p>');
  L.push(indent(flowchart, 4));
  L.push('  </div>');
  L.push('  <p class="case-stamp"><span class="mono">Case v' + facts.case_version + ' ' + '__STAMP__' + '</span></p>');
  L.push('</div>');
  L.push('<script>');
  L.push('/* Case tabs and the generated COLE constant. Generated by');
  L.push('   scripts/inject-case.mjs from scripts/case-facts.json. Exercise code reads');
  L.push('   figures from COLE; a number typed into an exercise is the defect this');
  L.push('   prevents. Do not edit inside the sentinels: edit CASE.md and rebuild. */');
  L.push('var COLE=' + JSON.stringify(F) + ';');
  L.push('(function(){');
  L.push("  var tabs=[document.getElementById('caseTabFacts'),document.getElementById('caseTabStruct')];");
  L.push("  var panels=[document.getElementById('casePanelFacts'),document.getElementById('casePanelStruct')];");
  L.push('  if(!tabs[0]||!tabs[1]||!panels[0]||!panels[1])return;');
  L.push('  function show(i){');
  L.push('    for(var k=0;k<2;k++){');
  L.push("      tabs[k].className='case-tab'+(k===i?' on':'');");
  L.push("      tabs[k].setAttribute('aria-selected',k===i?'true':'false');");
  L.push("      tabs[k].tabIndex=k===i?0:-1;");
  L.push("      panels[k].className='case-panel'+(k===i?'':' case-off');");
  L.push('    }');
  L.push('  }');
  L.push('  for(var i=0;i<2;i++)(function(i){');
  L.push("    tabs[i].addEventListener('click',function(){show(i)});");
  L.push("    tabs[i].addEventListener('keydown',function(e){");
  L.push("      if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();var n=1-i;show(n);tabs[n].focus()}");
  L.push('    });');
  L.push('  })(i);');
  L.push('})();');
  L.push('</script>');
  const body = L.join('\n');
  const stamp = createHash('sha256').update(body.replace('__STAMP__', ''), 'utf8').digest('hex').slice(0, 7);
  return { body: body.replace('__STAMP__', stamp), stamp };
}

function indent(s, n) {
  const pad = ' '.repeat(n);
  return s.split('\n').map((l) => (l.trim() ? pad + l : l)).join('\n');
}

export function regionFor(block, stamp) {
  return OPEN + '\n' +
         `<!-- generated by scripts/inject-case.mjs from CASE.md v${facts.case_version} · sha256 ${sha256(block)} · do not edit between the sentinels -->\n` +
         block + '\n' + CLOSE;
}
export function sha256(s) { return createHash('sha256').update(s, 'utf8').digest('hex'); }
export { OPEN, CLOSE, facts };

/* ---------------------------------------------------------------- main -- */
if (import.meta.url === `file://${process.argv[1]}`) {
  const check = process.argv.includes('--check');
  const { body, stamp } = buildBlock();
  const region = regionFor(body, stamp);
  let changed = 0, missing = [];
  for (const rel of LESSONS) {
    const path = join(REPO, rel);
    const text = readFileSync(path, 'utf8');
    const a = text.indexOf(OPEN), b = text.indexOf(CLOSE);
    if (a < 0 || b < 0) { missing.push(rel); continue; }
    const next = text.slice(0, a) + region + text.slice(b + CLOSE.length);
    if (next === text) { console.log(`OK    current  ${rel}`); continue; }
    changed++;
    if (check) { console.log(`STALE          ${rel}`); }
    else { writeFileSync(path, next); console.log(`WROTE          ${rel}`); }
  }
  for (const m of missing) console.log(`FAIL  no sentinels  ${m}`);
  console.log(`summary: ${LESSONS.length - changed - missing.length} current, ${changed} ${check ? 'stale' : 'rewritten'}, ${missing.length} without sentinels  ·  stamp ${stamp}`);
  process.exit(missing.length || (check && changed) ? 1 : 0);
}
