#!/usr/bin/env node
/**
 * verify-sources.mjs — recompute the SHA-256 of every injected source list and
 * fail on drift. Non-zero exit is the point.
 *
 * THREE INDEPENDENT FAILURES, REPORTED SEPARATELY AND IN THE SAME WORDS
 * verify-case.mjs uses, because a maintainer reading a failure should not have
 * to learn a second vocabulary:
 *   1. a lesson has no sentinels                     -> inject-sources has never run there
 *   2. the recorded hash does not match the content  -> somebody hand-edited inside
 *   3. the content does not match the current build  -> SOURCES.md changed, rebuild
 *
 * It also reports two things only this file can see, because they are about the
 * relationship between the register and the corpus rather than about drift:
 *   - a chip pointing at a key SOURCES.md does not define
 *   - a source declared for a lesson that the lesson never cites, split by
 *     whether its kind exempts it from carrying a chip
 */
import { readFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { model, LESSONS, isAbsent, UNVERIFIED } from './build-sources.mjs';
import { OPEN, CLOSE, sha256, buildBlock } from './inject-sources.mjs';

const REPO = join(dirname(fileURLToPath(import.meta.url)), '..');
const sources = model();
let fails = 0;

for (const lesson of LESSONS) {
  const text = readFileSync(join(REPO, lesson, 'index.html'), 'utf8');
  const a = text.indexOf(OPEN), b = text.indexOf(CLOSE);
  if (a < 0 || b < 0) { console.log(`FAIL  ${lesson}  no sentinels`); fails++; continue; }
  const region = text.slice(a + OPEN.length, b);
  const recorded = region.match(/sha256 ([0-9a-f]{64})/);
  if (!recorded) { console.log(`FAIL  ${lesson}  no recorded hash after the opening sentinel`); fails++; continue; }
  const content = region.replace(/^\n<!-- generated by[^\n]*-->\n/, '').replace(/\n$/, '');
  const actual = sha256(content);
  const expected = sha256(buildBlock(sources, lesson));
  if (actual !== recorded[1]) {
    console.log(`FAIL  ${lesson}  block was hand-edited`);
    console.log(`        recorded ${recorded[1].slice(0, 16)}  actual ${actual.slice(0, 16)}`);
    fails++;
  } else if (actual !== expected) {
    console.log(`FAIL  ${lesson}  block is stale against the current SOURCES.md build`);
    console.log(`        injected ${actual.slice(0, 16)}  expected ${expected.slice(0, 16)}  (run scripts/inject-sources.mjs)`);
    fails++;
  } else {
    console.log(`OK    ${lesson}  sha256 ${actual.slice(0, 16)}`);
  }
}

/* ---- what only the register can see -------------------------------------- */

if (sources.dangling) {
  console.log('');
  for (const d of sources.dangling) { console.log(`FAIL  ${d}`); fails++; }
}

const declaredUncited = [];
for (const rec of sources.values()) {
  for (const lesson of Object.keys(rec.used_for)) {
    if (rec.cited_by.some((c) => c.lesson === lesson)) continue;
    declaredUncited.push({ lesson, rec });
  }
}
const exempt = declaredUncited.filter((x) => x.rec.chip_exempt);
const notExempt = declaredUncited.filter((x) => !x.rec.chip_exempt);
console.log('');
console.log(`----  ${exempt.length} source(s) listed without a chip and exempt by kind`);
for (const { lesson, rec } of exempt) console.log(`        ${lesson.padEnd(11)} ${rec.key.padEnd(24)} ${rec.kind}`);
if (notExempt.length) {
  console.log(`ADVISE ${notExempt.length} source(s) listed by a lesson that never cites them, and NOT exempt by kind`);
  for (const { lesson, rec } of notExempt) {
    console.log(`        ${lesson.padEnd(11)} ${rec.key.padEnd(24)} kind=${rec.kind} — either a missing chip or a source that does not belong in this lesson`);
  }
}

const gaps = [...sources.values()].filter((r) =>
  ['author', 'publisher', 'link', 'published', 'last_retrieved'].some((f) => isAbsent(r[f]) && r[f] !== 'not applicable'));
console.log(`----  ${gaps.length} record(s) carry at least one ${UNVERIFIED} field; BIBLIOGRAPHY.md prints every one`);

/* ---- disclose_on_page, and the check that it is what gates the disclosure -- */
/* SOURCES.md declares disclose_on_page as "the page must say so where they
   appear". Until Phase 4 build-sources.mjs parsed it into a boolean and NOTHING
   READ IT, so the flag that mandates a page disclosure had no consumer and the
   disclosure it guards reached the reader only where somebody wrote it into the
   prose by hand. That is how the synthetic-case disclosure came off all four
   lesson footers when Phase 3 canonicalised src-case: the arbitration kept every
   clause in the record's `scope`, and the renderer had never emitted `scope`.
   Nobody chose it; nothing was watching.

   inject-sources.mjs renderEntry() NOW EMITS rec.scope, and only when
   rec.disclose_on_page === true. This block is the check on that gate, and it
   tests BOTH directions, because a gate that only ever fires open is not a gate:

     1. every record with the flag renders its scope in every citing lesson
     2. every record without the flag renders no scope anywhere

   Both are hard failures. Direction 1 catches a footer that stopped carrying a
   disclosure it is owed; direction 2 catches a maintainer-facing scope note
   leaking onto a student-facing page. Neither can go quiet again.

   docs/repo-updates-plan.md §16.6(c); docs/deferred-work.md DW-011. */
const footers = new Map(LESSONS.map((l) => [l, readFileSync(join(REPO, l, 'index.html'), 'utf8')]));
/* The comparison probe is the scope's FIRST SENTENCE, capped, because that is
   the clause a reader would recognise and it survives the entity escaping the
   renderer applies to the rest. An empty probe means there is nothing to look
   for and the record is not testable either way. */
const probe = (rec) => (rec.scope || '').split(/\.\s/)[0].slice(0, 40).trim();
const entryFor = (lesson, key) => {
  const m = (footers.get(lesson) || '').match(new RegExp(`<li id="${key}"[^>]*>([\\s\\S]*?)</li>`));
  return m ? m[1] : null;
};

const disclosed = [...sources.values()].filter((r) => r.disclose_on_page);
console.log('');
console.log(`----  ${disclosed.length} record(s) set disclose_on_page: true`);
for (const rec of disclosed) {
  const p = probe(rec);
  const lessons = Object.keys(rec.used_for);
  const missing = p ? lessons.filter((l) => {
    const li = entryFor(l, rec.key);
    return li === null || !li.includes(p);
  }) : [];
  if (!p) {
    console.log(`FAIL  ${rec.key} sets disclose_on_page: true and carries no scope to disclose`);
    fails++;
  } else if (missing.length) {
    console.log(`FAIL  ${rec.key} declares disclose_on_page: true and its scope is not rendered in ${missing.join(', ')}`);
    console.log('        renderEntry() emits rec.scope behind that flag, so a footer without it is');
    console.log('        drift, not a decision. Run scripts/inject-sources.mjs.');
    fails++;
  } else {
    console.log(`OK    ${rec.key.padEnd(24)} kind=${rec.kind.padEnd(16)} scope rendered in ${lessons.join(', ')}`);
  }
}

/* Direction 2. A record that does NOT set the flag must not have its scope on a
   page: most scope notes are written to the maintainer, not to the reader. */
let leaked = 0;
for (const rec of sources.values()) {
  if (rec.disclose_on_page) continue;
  const p = probe(rec);
  if (!p) continue;
  for (const lesson of Object.keys(rec.used_for)) {
    const li = entryFor(lesson, rec.key);
    if (li && li.includes(p)) {
      console.log(`FAIL  ${rec.key} does not set disclose_on_page and its scope is rendered in ${lesson}`);
      fails++; leaked++;
    }
  }
}
if (!leaked) console.log(`----  0 record(s) render a scope without disclose_on_page: true`);

console.log(`\nsummary: ${LESSONS.length - fails} of ${LESSONS.length} lessons carry the current SOURCES.md block`);
process.exit(fails ? 1 : 0);
