#!/usr/bin/env node
/**
 * verify-case.mjs — recompute the SHA-256 of every injected block and fail on
 * drift. Non-zero exit is the point: this is meant to run in CI and to be the
 * check a human runs before pushing.
 *
 * Three independent failures are reported separately, because they have
 * different causes:
 *   1. a lesson has no sentinels                     -> inject-case has never run there
 *   2. the recorded hash does not match the content  -> somebody hand-edited inside
 *   3. the content does not match the current build  -> CASE.md changed, rebuild
 */
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { LESSONS, buildBlock, OPEN, CLOSE, sha256, facts } from './inject-case.mjs';

const REPO = join(dirname(fileURLToPath(import.meta.url)), '..');
const { body: expected } = buildBlock();
const expectedHash = sha256(expected);
let fails = 0;

for (const rel of LESSONS) {
  const text = readFileSync(join(REPO, rel), 'utf8');
  const a = text.indexOf(OPEN), b = text.indexOf(CLOSE);
  if (a < 0 || b < 0) { console.log(`FAIL  ${rel}  no sentinels`); fails++; continue; }
  const region = text.slice(a + OPEN.length, b);
  const recorded = region.match(/sha256 ([0-9a-f]{64})/);
  if (!recorded) { console.log(`FAIL  ${rel}  no recorded hash after the opening sentinel`); fails++; continue; }
  const content = region.replace(/^\n<!-- generated by[^\n]*-->\n/, '').replace(/\n$/, '');
  const actual = sha256(content);
  if (actual !== recorded[1]) {
    console.log(`FAIL  ${rel}  block was hand-edited`);
    console.log(`        recorded ${recorded[1].slice(0, 16)}  actual ${actual.slice(0, 16)}`);
    fails++;
  } else if (actual !== expectedHash) {
    console.log(`FAIL  ${rel}  block is stale against the current CASE.md build`);
    console.log(`        injected ${actual.slice(0, 16)}  expected ${expectedHash.slice(0, 16)}  (run scripts/build-case.mjs then scripts/inject-case.mjs)`);
    fails++;
  } else {
    console.log(`OK    ${rel}  sha256 ${actual.slice(0, 16)}`);
  }
}
console.log(`summary: ${LESSONS.length - fails} of ${LESSONS.length} lessons carry the current CASE.md v${facts.case_version} block`);
process.exit(fails ? 1 : 0);
